packages:
  - packages/*
  - examples/*

allowBuilds:
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@jameslnewell/editor-config@7.0.0'
  - '@jameslnewell/eslint-config@7.0.0'
  - '@jameslnewell/prettier-config@7.0.0'
  - '@jameslnewell/typescript-config@7.0.0'
  - '@jameslnewell/vitest-config@7.0.0'
