packages:
  - packages/*

allowBuilds:
  unrs-resolver: false

minimumReleaseAgeExclude:
  - '@jameslnewell/eslint-config@7.0.0'
  - '@jameslnewell/typescript-config@7.0.0'
  - '@jameslnewell/vitest-config@7.0.0'
