packages:
  - packages/*
  - examples/*

minimumReleaseAgeExclude:
  - '@jameslnewell/editor-config@8.0.0'
  - '@jameslnewell/eslint-config@8.0.0'
  - '@jameslnewell/prettier-config@8.0.0'
  - '@jameslnewell/typescript-config@8.0.0'
  - '@jameslnewell/vitest-config@8.0.0'
